theme: jekyll-theme-leap-day


comments:
  provider: "disqus"
  disqus:
    shortname: "ranghee"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-165999993-1"
    anonymize_ip: false # default
